import type { GitHub } from "@actions/github/lib/utils.js";
import type { ChangedFile, DocRecommendation } from "./types.js";

type Octokit = InstanceType<typeof GitHub>;

interface ReviewComment {
  path: string;
  body: string;
  line: number;
  side: "RIGHT";
}

function buildSuggestionBody(rec: DocRecommendation): string {
  const parts: string[] = [];
  parts.push(`**Doc Review:** ${rec.reasoning}\n`);
  if (rec.suggestedContent != null) {
    parts.push("```suggestion");
    parts.push(rec.suggestedContent);
    parts.push("```");
  }
  return parts.join("\n");
}

function buildSummarySection(rec: DocRecommendation): string {
  if (rec.type === "create") {
    return `### New documentation needed: \`${rec.file}\`\n\n${rec.reasoning}`;
  }

  // Update for a file not in the diff
  const parts: string[] = [];
  parts.push(`### Update needed: \`${rec.file}\``);
  if (rec.startLine != null) {
    parts.push(
      `Lines ${rec.startLine}${rec.endLine != null && rec.endLine !== rec.startLine ? `-${rec.endLine}` : ""}`
    );
  }
  parts.push(`\n${rec.reasoning}`);
  if (rec.suggestedContent != null) {
    parts.push("\n**Suggested replacement:**");
    parts.push("```");
    parts.push(rec.suggestedContent);
    parts.push("```");
  }
  return parts.join("\n");
}

export async function postReview(
  octokit: Octokit,
  owner: string,
  repo: string,
  pullNumber: number,
  recommendations: DocRecommendation[],
  changedFiles: ChangedFile[]
): Promise<void> {
  if (recommendations.length === 0) return;

  const changedFileSet = new Set(changedFiles.map((f) => f.filename));

  // Separate inline-eligible from summary-only
  const inlineComments: ReviewComment[] = [];
  const summaryItems: string[] = [];

  for (const rec of recommendations) {
    if (
      rec.type === "update" &&
      changedFileSet.has(rec.file) &&
      rec.endLine != null
    ) {
      // This doc file is in the PR diff — we can post inline
      inlineComments.push({
        path: rec.file,
        body: buildSuggestionBody(rec),
        line: rec.endLine,
        side: "RIGHT",
      });
    } else {
      // Not in PR diff, or a "create" recommendation — goes to summary
      summaryItems.push(buildSummarySection(rec));
    }
  }

  // Post inline review if we have any
  if (inlineComments.length > 0) {
    await octokit.rest.pulls.createReview({
      owner,
      repo,
      pull_number: pullNumber,
      event: "COMMENT",
      body: "📖 **Doc Review** found documentation that may need updating based on these code changes.",
      comments: inlineComments,
    });
  }

  // Post summary comment for non-inline recommendations
  if (summaryItems.length > 0) {
    const body = [
      "## 📖 Documentation Review\n",
      "The following documentation changes are recommended based on the code changes in this PR:\n",
      ...summaryItems,
      "\n---\n*Generated by [doc-review-action](https://github.com/RLProteus/doc-review-action)*",
    ].join("\n");

    await octokit.rest.issues.createComment({
      owner,
      repo,
      issue_number: pullNumber,
      body,
    });
  }
}
